site_name: Recursos docentes de Rubén Guillem

theme:
  name: material
  language: es

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition

nav:
  - Inicio: index.md

  - Física y Química:
      - Presentación: fisica-quimica/index.md
      - 1.º de Bachillerato:
          - Presentación: fisica-quimica/1-bach/index.md
          - Cinemática: fisica-quimica/1-bach/cinematica.md
          - Dinámica: fisica-quimica/1-bach/dinamica.md

  - Matemáticas: matematicas/index.md
  - Tecnología: tecnologia/index.md
  - Digitalización: digitalizacion/index.md
  - Actividades y proyectos: actividades/index.md